/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf --transform 
Files: scene.gltf [218.28KB] > D:\myhomepage\Myhomepage\3dModels\Wizard\scene-transformed.glb [3.75MB] (-1617%)
Author: elbertwithane (https://sketchfab.com/elbertwithane)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tim-mckee-boy-wizard-900beec6d3504d51ade81cb5c052163b
Title: Tim Mckee - Boy Wizard
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Evil_Hathattty_mesh_Evil_HatBLN_Hat_0.geometry} material={materials.Evil_HatBLN_Hat} position={[0.001, 0, 0]} rotation={[0, 0.224, 0]} scale={16.649} />
      <mesh geometry={nodes.WandpCylinder1_Wandq_0.geometry} material={materials.PaletteMaterial001} position={[0.001, 0, 0]} rotation={[0, 0.224, 0]} scale={16.649} />
      <mesh geometry={nodes.R_shoe_tongue_mesh_BLN_Shoe_tongue_0.geometry} material={materials.BLN_Shoe_tongue} position={[0.001, 0, 0]} rotation={[0, 0.224, 0]} scale={16.649} />
      <mesh geometry={nodes.Chest_piece_mesh_BLN_chest_piece_0.geometry} material={materials.BLN_chest_piece} position={[0.001, 0, 0]} rotation={[0, 0.224, 0]} scale={16.649} />
      <mesh geometry={nodes.Right_Eyeball_Mesh_Lam_eyeball_0.geometry} material={materials.material_0} position={[0.001, 0, 0]} rotation={[0, 0.224, 0]} scale={16.649} />
      <mesh geometry={nodes.pants_mesh_BLN_Pants_0.geometry} material={materials.BLN_Pants} position={[0.001, 0, 0]} rotation={[0, 0.224, 0]} scale={16.649} />
      <mesh geometry={nodes.lower_coat_mesh_FK_BLN_Lower_coat_0.geometry} material={materials.BLN_Lower_coat} position={[0.001, 0, 0]} rotation={[0, 0.224, 0]} scale={16.649} />
      <mesh geometry={nodes.R_shoe_mesh_BLN_shoes_0.geometry} material={materials.BLN_shoes} position={[0.001, 0, 0]} rotation={[0, 0.224, 0]} scale={16.649} />
      <mesh geometry={nodes.Upper_coat_mesh_BLN_upper_coat_0.geometry} material={materials.BLN_upper_coat} position={[0.001, 0, 0]} rotation={[0, 0.224, 0]} scale={16.649} />
      <mesh geometry={nodes.upper_body_mesh_BLN_shirt_0.geometry} material={materials.BLN_shirt} position={[0.001, 0, 0]} rotation={[0, 0.224, 0]} scale={16.649} />
      <mesh geometry={nodes.upper_body_mesh_BLN_Shirt_collar_0.geometry} material={materials.BLN_Shirt_collar} position={[0.001, 0, 0]} rotation={[0, 0.224, 0]} scale={16.649} />
      <mesh geometry={nodes.Coat_collar_mesh_BLN_collar_piece_0.geometry} material={materials.BLN_collar_piece} position={[0.001, 0, 0]} rotation={[0, 0.224, 0]} scale={16.649} />
      <mesh geometry={nodes.BookpolySurface5_Bookblinn1_0.geometry} material={materials.Bookblinn1} position={[0.001, 0, 0]} rotation={[0, 0.224, 0]} scale={16.649} />
      <mesh geometry={nodes.BookBook_corner_mesh4_Booklam_book_corners_0.geometry} material={materials.Booklam_book_corners} position={[0.001, 0, 0]} rotation={[0, 0.224, 0]} scale={16.649} />
      <mesh geometry={nodes.BookpolySurface20_BookBLN_Metal_parts_0.geometry} material={materials.BookBLN_Metal_parts} position={[0.001, 0, 0]} rotation={[0, 0.224, 0]} scale={16.649} />
      <mesh geometry={nodes.BookFront_glow_mesh_Booklambert8_0.geometry} material={materials.PaletteMaterial002} position={[0.001, 0, 0]} rotation={[0, 0.224, 0]} scale={16.649} />
      <mesh geometry={nodes.BookpolySurface2_BookBLN_Book_covers_0.geometry} material={materials.BookBLN_Book_covers} position={[0.001, 0, 0]} rotation={[0, 0.224, 0]} scale={16.649} />
      <mesh geometry={nodes.BookpCube10_Booklam_front_bits_0.geometry} material={materials.material_2} position={[0.001, 0, 0]} rotation={[0, 0.224, 0]} scale={16.649} />
      <mesh geometry={nodes.BookpolySurface28_Booklam_back_bits_0.geometry} material={materials.Booklam_back_bits} position={[0.001, 0, 0]} rotation={[0, 0.224, 0]} scale={16.649} />
      <mesh geometry={nodes.Evil_HatpPlane1_Evil_HatsolidShader_0.geometry} material={materials.PaletteMaterial003} position={[0.001, 0, 0]} rotation={[0, 0.224, 0]} scale={16.649} />
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
