/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

"use client"
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function BlueBird(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/bluebird mouth.glb')
  const { actions, names } = useAnimations(animations, group)
  
  // 애니메이션 위치를 중심에 맞춰 조정
  useFrame((state, delta, xrFrame) => {
    // 기본 위치가 [0, 1, 1]이고, 거기서 위아래로 움직이게 함
    group.current.position.y = -0.7 + Math.sin(state.clock.elapsedTime) * 0.08;
  })

  // 컴포넌트 마운트 시 애니메이션 자동 재생 - 첫 번째 애니메이션만 재생
  React.useEffect(() => {
    if (names.length > 0) {
      // 모든 애니메이션 중 첫 번째 애니메이션만 재생
      actions[names[0]]?.reset().play();
    }
    
    // 모든 가능한 애니메이션 이름 로깅
    console.log("Available animations:", names);
  }, [actions, names]);

  return (
    <group 
      ref={group} 
      {...props} 
      dispose={null}
      position={[0, 1, 0]}
      scale={[0.09, 0.09, 0.09]} // 크기
      rotation={[0.1, -0.55, 0]}
    >
      <group name="Scene">
        <group name="Armature">
          <skinnedMesh
            name="eastern_bluebird"
            geometry={nodes.eastern_bluebird.geometry}
            material={materials.bluebird}
            skeleton={nodes.eastern_bluebird.skeleton}
            morphTargetDictionary={nodes.eastern_bluebird.morphTargetDictionary}
            morphTargetInfluences={nodes.eastern_bluebird.morphTargetInfluences}
            castShadow
            receiveShadow
          />
          <primitive object={nodes.Root_M} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/bluebird mouth.glb') 